# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Configurator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configurator(object):
    def setupUi(self, configurator):
        configurator.setObjectName("configurator")
        configurator.setWindowModality(QtCore.Qt.WindowModal)
        configurator.resize(921, 713)
        configurator.setStyleSheet("QpushButton { margin: 0,0,0,25 px; }")
        configurator.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(configurator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_options = QtWidgets.QLabel(configurator)
        self.label_options.setObjectName("label_options")
        self.verticalLayout.addWidget(self.label_options)
        self.horizontal_layout_header = QtWidgets.QHBoxLayout()
        self.horizontal_layout_header.setObjectName("horizontal_layout_header")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(configurator)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.lineEdit_Name = QtWidgets.QLineEdit(configurator)
        self.lineEdit_Name.setInputMask("")
        self.lineEdit_Name.setText("")
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.verticalLayout_5.addWidget(self.lineEdit_Name)
        self.label_2 = QtWidgets.QLabel(configurator)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.comboBox_type = QtWidgets.QComboBox(configurator)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_type)
        self.label_size = QtWidgets.QLabel(configurator)
        self.label_size.setObjectName("label_size")
        self.verticalLayout_5.addWidget(self.label_size)
        self.comboBox_size = QtWidgets.QComboBox(configurator)
        self.comboBox_size.setObjectName("comboBox_size")
        self.verticalLayout_5.addWidget(self.comboBox_size)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_speed = QtWidgets.QLabel(configurator)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout_11.addWidget(self.label_speed)
        self.comboBox_speed = QtWidgets.QComboBox(configurator)
        self.comboBox_speed.setObjectName("comboBox_speed")
        self.horizontalLayout_11.addWidget(self.comboBox_speed)
        self.spinBox_speed = QtWidgets.QSpinBox(configurator)
        self.spinBox_speed.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.horizontalLayout_11.addWidget(self.spinBox_speed)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontal_layout_header.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_WIS = QtWidgets.QLabel(configurator)
        self.label_WIS.setObjectName("label_WIS")
        self.horizontalLayout_7.addWidget(self.label_WIS)
        self.label_INT = QtWidgets.QLabel(configurator)
        self.label_INT.setObjectName("label_INT")
        self.horizontalLayout_7.addWidget(self.label_INT)
        self.label_CHA = QtWidgets.QLabel(configurator)
        self.label_CHA.setObjectName("label_CHA")
        self.horizontalLayout_7.addWidget(self.label_CHA)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinBox_WIS = QtWidgets.QSpinBox(configurator)
        self.spinBox_WIS.setMaximum(30)
        self.spinBox_WIS.setProperty("value", 10)
        self.spinBox_WIS.setObjectName("spinBox_WIS")
        self.horizontalLayout_8.addWidget(self.spinBox_WIS)
        self.spinBox_INT = QtWidgets.QSpinBox(configurator)
        self.spinBox_INT.setMaximum(30)
        self.spinBox_INT.setProperty("value", 10)
        self.spinBox_INT.setObjectName("spinBox_INT")
        self.horizontalLayout_8.addWidget(self.spinBox_INT)
        self.spinBox_CHA = QtWidgets.QSpinBox(configurator)
        self.spinBox_CHA.setMaximum(30)
        self.spinBox_CHA.setProperty("value", 10)
        self.spinBox_CHA.setObjectName("spinBox_CHA")
        self.horizontalLayout_8.addWidget(self.spinBox_CHA)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_STR = QtWidgets.QLabel(configurator)
        self.label_STR.setEnabled(True)
        self.label_STR.setObjectName("label_STR")
        self.horizontalLayout_5.addWidget(self.label_STR)
        self.label_DEX = QtWidgets.QLabel(configurator)
        self.label_DEX.setObjectName("label_DEX")
        self.horizontalLayout_5.addWidget(self.label_DEX)
        self.label_CON = QtWidgets.QLabel(configurator)
        self.label_CON.setObjectName("label_CON")
        self.horizontalLayout_5.addWidget(self.label_CON)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_STR = QtWidgets.QSpinBox(configurator)
        self.spinBox_STR.setMaximum(30)
        self.spinBox_STR.setProperty("value", 10)
        self.spinBox_STR.setObjectName("spinBox_STR")
        self.horizontalLayout_6.addWidget(self.spinBox_STR)
        self.spinBox_DEX = QtWidgets.QSpinBox(configurator)
        self.spinBox_DEX.setMaximum(30)
        self.spinBox_DEX.setProperty("value", 10)
        self.spinBox_DEX.setObjectName("spinBox_DEX")
        self.horizontalLayout_6.addWidget(self.spinBox_DEX)
        self.spinBox_CON = QtWidgets.QSpinBox(configurator)
        self.spinBox_CON.setMaximum(30)
        self.spinBox_CON.setProperty("value", 10)
        self.spinBox_CON.setObjectName("spinBox_CON")
        self.horizontalLayout_6.addWidget(self.spinBox_CON)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.pushButton_clear = QtWidgets.QPushButton(configurator)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_6.addWidget(self.pushButton_clear)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(configurator)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.spinBox_group = QtWidgets.QSpinBox(configurator)
        self.spinBox_group.setProperty("value", 1)
        self.spinBox_group.setObjectName("spinBox_group")
        self.horizontalLayout_9.addWidget(self.spinBox_group)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(configurator)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.spinBox_CR = QtWidgets.QSpinBox(configurator)
        self.spinBox_CR.setMaximum(30)
        self.spinBox_CR.setProperty("value", 10)
        self.spinBox_CR.setObjectName("spinBox_CR")
        self.horizontalLayout_10.addWidget(self.spinBox_CR)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontal_layout_header.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontal_layout_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_search = QtWidgets.QLineEdit(configurator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setMaximumSize(QtCore.QSize(452, 16777215))
        self.lineEdit_search.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_search)
        self.label_selection = QtWidgets.QLabel(configurator)
        self.label_selection.setObjectName("label_selection")
        self.horizontalLayout_2.addWidget(self.label_selection)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_catagory = QtWidgets.QListWidget(configurator)
        self.listWidget_catagory.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_catagory.setObjectName("listWidget_catagory")
        self.verticalLayout_4.addWidget(self.listWidget_catagory)
        self.pushButton_add = QtWidgets.QPushButton(configurator)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_4.addWidget(self.pushButton_add)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_options = QtWidgets.QListWidget(configurator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_options.sizePolicy().hasHeightForWidth())
        self.listWidget_options.setSizePolicy(sizePolicy)
        self.listWidget_options.setStyleSheet("QpushButton { margin-left: 25px; }")
        self.listWidget_options.setObjectName("listWidget_options")
        self.verticalLayout_3.addWidget(self.listWidget_options)
        self.pushButton_reset = QtWidgets.QPushButton(configurator)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_3.addWidget(self.pushButton_reset)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_create = QtWidgets.QPushButton(configurator)
        self.pushButton_create.setObjectName("pushButton_create")
        self.verticalLayout.addWidget(self.pushButton_create)
        self.pushButton_back = QtWidgets.QPushButton(configurator)
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.pushButton_back)

        self.retranslateUi(configurator)
        QtCore.QMetaObject.connectSlotsByName(configurator)

    def retranslateUi(self, configurator):
        _translate = QtCore.QCoreApplication.translate
        configurator.setWindowTitle(_translate("configurator", "Characteristics"))
        self.label_options.setText(_translate("configurator", "Search and select Items here."))
        self.label_13.setText(_translate("configurator", "Name:"))
        self.lineEdit_Name.setPlaceholderText(_translate("configurator", "***"))
        self.label_2.setText(_translate("configurator", "Type:"))
        self.comboBox_type.setItemText(0, _translate("configurator", "creature"))
        self.comboBox_type.setItemText(1, _translate("configurator", "trap"))
        self.comboBox_type.setItemText(2, _translate("configurator", "social"))
        self.label_size.setText(_translate("configurator", "Size"))
        self.label_speed.setText(_translate("configurator", "Speed:"))
        self.label_WIS.setText(_translate("configurator", "WIS"))
        self.label_INT.setText(_translate("configurator", "INT"))
        self.label_CHA.setText(_translate("configurator", "CHA"))
        self.label_STR.setText(_translate("configurator", "STR"))
        self.label_DEX.setText(_translate("configurator", "DEX"))
        self.label_CON.setText(_translate("configurator", "CON"))
        self.pushButton_clear.setText(_translate("configurator", "Reset Stats"))
        self.label_14.setText(_translate("configurator", "Group of:"))
        self.label_4.setText(_translate("configurator", "TARGET CR:"))
        self.lineEdit_search.setPlaceholderText(_translate("configurator", "Search"))
        self.label_selection.setText(_translate("configurator", "Collected selections here:"))
        self.pushButton_add.setToolTip(_translate("configurator", "Add an item to the list"))
        self.pushButton_add.setText(_translate("configurator", "Add"))
        self.pushButton_reset.setText(_translate("configurator", "Reset"))
        self.pushButton_create.setToolTip(_translate("configurator", "Add your creation to the DM vault.."))
        self.pushButton_create.setText(_translate("configurator", "Create!"))
        self.pushButton_back.setText(_translate("configurator", "Back (Esc)"))
