# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Encounter_Dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Encounter(object):
    def setupUi(self, Encounter):
        Encounter.setObjectName(_fromUtf8("Encounter"))
        Encounter.resize(891, 684)
        self.listWidget_Display = QtGui.QListWidget(Encounter)
        self.listWidget_Display.setGeometry(QtCore.QRect(20, 20, 591, 641))
        self.listWidget_Display.setProperty("showDropIndicator", False)
        self.listWidget_Display.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.listWidget_Display.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget_Display.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_Display.setWordWrap(True)
        self.listWidget_Display.setObjectName(_fromUtf8("listWidget_Display"))
        self.verticalLayoutWidget = QtGui.QWidget(Encounter)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 10, 241, 651))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.lineEdit_Name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_Name.setObjectName(_fromUtf8("lineEdit_Name"))
        self.verticalLayout.addWidget(self.lineEdit_Name)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_type = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_type.setObjectName(_fromUtf8("comboBox_type"))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox_type)
        self.label_size = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_size.setObjectName(_fromUtf8("label_size"))
        self.verticalLayout.addWidget(self.label_size)
        self.comboBox_size = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_size.setObjectName(_fromUtf8("comboBox_size"))
        self.verticalLayout.addWidget(self.comboBox_size)
        self.label_speed = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_speed.setObjectName(_fromUtf8("label_speed"))
        self.verticalLayout.addWidget(self.label_speed)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBox_speed = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_speed.setObjectName(_fromUtf8("comboBox_speed"))
        self.horizontalLayout_6.addWidget(self.comboBox_speed)
        self.spinBox_speed = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_speed.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_speed.setObjectName(_fromUtf8("spinBox_speed"))
        self.horizontalLayout_6.addWidget(self.spinBox_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_STR = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_STR.setEnabled(True)
        self.label_STR.setObjectName(_fromUtf8("label_STR"))
        self.horizontalLayout.addWidget(self.label_STR)
        self.label_DEX = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_DEX.setObjectName(_fromUtf8("label_DEX"))
        self.horizontalLayout.addWidget(self.label_DEX)
        self.label_CON = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_CON.setObjectName(_fromUtf8("label_CON"))
        self.horizontalLayout.addWidget(self.label_CON)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.spinBox_STR = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_STR.setMaximum(30)
        self.spinBox_STR.setProperty("value", 10)
        self.spinBox_STR.setObjectName(_fromUtf8("spinBox_STR"))
        self.horizontalLayout_2.addWidget(self.spinBox_STR)
        self.spinBox_DEX = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_DEX.setMaximum(30)
        self.spinBox_DEX.setProperty("value", 10)
        self.spinBox_DEX.setObjectName(_fromUtf8("spinBox_DEX"))
        self.horizontalLayout_2.addWidget(self.spinBox_DEX)
        self.spinBox_CON = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_CON.setMaximum(30)
        self.spinBox_CON.setProperty("value", 10)
        self.spinBox_CON.setObjectName(_fromUtf8("spinBox_CON"))
        self.horizontalLayout_2.addWidget(self.spinBox_CON)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_WIS = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_WIS.setObjectName(_fromUtf8("label_WIS"))
        self.horizontalLayout_3.addWidget(self.label_WIS)
        self.label_INT = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_INT.setObjectName(_fromUtf8("label_INT"))
        self.horizontalLayout_3.addWidget(self.label_INT)
        self.label_CHA = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_CHA.setObjectName(_fromUtf8("label_CHA"))
        self.horizontalLayout_3.addWidget(self.label_CHA)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinBox_WIS = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_WIS.setMaximum(30)
        self.spinBox_WIS.setProperty("value", 10)
        self.spinBox_WIS.setObjectName(_fromUtf8("spinBox_WIS"))
        self.horizontalLayout_4.addWidget(self.spinBox_WIS)
        self.spinBox_INT = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_INT.setMaximum(30)
        self.spinBox_INT.setProperty("value", 10)
        self.spinBox_INT.setObjectName(_fromUtf8("spinBox_INT"))
        self.horizontalLayout_4.addWidget(self.spinBox_INT)
        self.spinBox_CHA = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_CHA.setMaximum(30)
        self.spinBox_CHA.setProperty("value", 10)
        self.spinBox_CHA.setObjectName(_fromUtf8("spinBox_CHA"))
        self.horizontalLayout_4.addWidget(self.spinBox_CHA)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_clear = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.pushButton_Select = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Select.setObjectName(_fromUtf8("pushButton_Select"))
        self.verticalLayout.addWidget(self.pushButton_Select)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_CR = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_CR.setMaximum(30)
        self.spinBox_CR.setProperty("value", 10)
        self.spinBox_CR.setObjectName(_fromUtf8("spinBox_CR"))
        self.horizontalLayout_5.addWidget(self.spinBox_CR)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.spinBox_group = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_group.setProperty("value", 1)
        self.spinBox_group.setObjectName(_fromUtf8("spinBox_group"))
        self.horizontalLayout_7.addWidget(self.spinBox_group)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.pushButton_Summon = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Summon.setObjectName(_fromUtf8("pushButton_Summon"))
        self.verticalLayout.addWidget(self.pushButton_Summon)
        self.pushButton_UnSummon = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_UnSummon.setObjectName(_fromUtf8("pushButton_UnSummon"))
        self.verticalLayout.addWidget(self.pushButton_UnSummon)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Encounter)
        QtCore.QMetaObject.connectSlotsByName(Encounter)

    def retranslateUi(self, Encounter):
        Encounter.setWindowTitle(_translate("Encounter", "Encounter Builder", None))
        self.label_13.setText(_translate("Encounter", "Name:", None))
        self.lineEdit_Name.setText(_translate("Encounter", "***", None))
        self.label_2.setText(_translate("Encounter", "Type:", None))
        self.comboBox_type.setItemText(0, _translate("Encounter", "creature", None))
        self.comboBox_type.setItemText(1, _translate("Encounter", "trap", None))
        self.comboBox_type.setItemText(2, _translate("Encounter", "social", None))
        self.label_size.setText(_translate("Encounter", "Size", None))
        self.label_speed.setText(_translate("Encounter", "Speed:", None))
        self.label_STR.setText(_translate("Encounter", "STR", None))
        self.label_DEX.setText(_translate("Encounter", "DEX", None))
        self.label_CON.setText(_translate("Encounter", "CON", None))
        self.label_WIS.setText(_translate("Encounter", "WIS", None))
        self.label_INT.setText(_translate("Encounter", "INT", None))
        self.label_CHA.setText(_translate("Encounter", "CHA", None))
        self.pushButton_clear.setText(_translate("Encounter", "Reset Stats", None))
        self.pushButton_Select.setText(_translate("Encounter", "Manage Characteristics", None))
        self.label_4.setText(_translate("Encounter", "TARGET CR:", None))
        self.label_14.setText(_translate("Encounter", "Group of:", None))
        self.pushButton_Summon.setText(_translate("Encounter", "Summon!", None))
        self.pushButton_UnSummon.setText(_translate("Encounter", "Un-Summon!", None))

