# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Vault_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vault(object):
    def setupUi(self, Vault):
        Vault.setObjectName("Vault")
        Vault.setWindowModality(QtCore.Qt.WindowModal)
        Vault.resize(925, 723)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Vault)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.listWidget_Display = QtWidgets.QListWidget(Vault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Display.sizePolicy().hasHeightForWidth())
        self.listWidget_Display.setSizePolicy(sizePolicy)
        self.listWidget_Display.setProperty("showDropIndicator", False)
        self.listWidget_Display.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_Display.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget_Display.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_Display.setWordWrap(True)
        self.listWidget_Display.setObjectName("listWidget_Display")
        self.horizontalLayout_10.addWidget(self.listWidget_Display)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButton_New = QtWidgets.QPushButton(Vault)
        self.pushButton_New.setObjectName("pushButton_New")
        self.verticalLayout.addWidget(self.pushButton_New)
        self.pushButton_delete = QtWidgets.QPushButton(Vault)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout.addWidget(self.pushButton_delete)
        self.pushButton_Summon = QtWidgets.QPushButton(Vault)
        self.pushButton_Summon.setObjectName("pushButton_Summon")
        self.verticalLayout.addWidget(self.pushButton_Summon)
        self.pushButton_UnSummon = QtWidgets.QPushButton(Vault)
        self.pushButton_UnSummon.setObjectName("pushButton_UnSummon")
        self.verticalLayout.addWidget(self.pushButton_UnSummon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Vault)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_load = QtWidgets.QPushButton(Vault)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_9.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(Vault)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_9.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_back = QtWidgets.QPushButton(Vault)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_8.addWidget(self.pushButton_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Vault)
        QtCore.QMetaObject.connectSlotsByName(Vault)

    def retranslateUi(self, Vault):
        _translate = QtCore.QCoreApplication.translate
        Vault.setWindowTitle(_translate("Vault", "DM Vault"))
        self.pushButton_New.setText(_translate("Vault", "New"))
        self.pushButton_delete.setToolTip(_translate("Vault", "Remove selected from current Encounter as well as DM Vault."))
        self.pushButton_delete.setText(_translate("Vault", "Delete"))
        self.pushButton_Summon.setToolTip(_translate("Vault", "Add Selected Items to Current Encounter"))
        self.pushButton_Summon.setText(_translate("Vault", "Copy to Encounter"))
        self.pushButton_UnSummon.setToolTip(_translate("Vault", "Remove Selected items from Current Encounter"))
        self.pushButton_UnSummon.setText(_translate("Vault", "Remove from Encounter"))
        self.label.setText(_translate("Vault", "(DM Vault Only)"))
        self.pushButton_load.setToolTip(_translate("Vault", "Load Encounter file"))
        self.pushButton_load.setText(_translate("Vault", "Load"))
        self.pushButton_save.setToolTip(_translate("Vault", "Save Encounter File"))
        self.pushButton_save.setText(_translate("Vault", "Save"))
        self.pushButton_back.setToolTip(_translate("Vault", "Go back to your encounter"))
        self.pushButton_back.setText(_translate("Vault", "⇦ Back (Esc)"))
