# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.listWidget_Encounter = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Encounter.setStyleSheet("font: 75 12pt \"Cantarell\";")
        self.listWidget_Encounter.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_Encounter.setObjectName("listWidget_Encounter")
        self.verticalLayout_3.addWidget(self.listWidget_Encounter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, 9, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Players = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Players.setObjectName("pushButton_Players")
        self.verticalLayout.addWidget(self.pushButton_Players)
        self.pushButton_Encounter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Encounter.setObjectName("pushButton_Encounter")
        self.verticalLayout.addWidget(self.pushButton_Encounter)
        self.pushButton_toggle_expand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toggle_expand.setObjectName("pushButton_toggle_expand")
        self.verticalLayout.addWidget(self.pushButton_toggle_expand)
        self.pushButton_Inititave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Inititave.setObjectName("pushButton_Inititave")
        self.verticalLayout.addWidget(self.pushButton_Inititave)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_main_initiative = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_main_initiative.setObjectName("spinBox_main_initiative")
        self.horizontalLayout_4.addWidget(self.spinBox_main_initiative)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spinBox_main_hp = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_main_hp.setMaximum(999)
        self.spinBox_main_hp.setObjectName("spinBox_main_hp")
        self.horizontalLayout_2.addWidget(self.spinBox_main_hp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_dam_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dam_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_dam_1.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_dam_1.setObjectName("pushButton_dam_1")
        self.horizontalLayout_3.addWidget(self.pushButton_dam_1)
        self.pushButton_dam_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dam_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_dam_3.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_dam_3.setObjectName("pushButton_dam_3")
        self.horizontalLayout_3.addWidget(self.pushButton_dam_3)
        self.pushButton_dam_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dam_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_dam_5.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_dam_5.setObjectName("pushButton_dam_5")
        self.horizontalLayout_3.addWidget(self.pushButton_dam_5)
        self.pushButton_dam_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dam_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_dam_10.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_dam_10.setObjectName("pushButton_dam_10")
        self.horizontalLayout_3.addWidget(self.pushButton_dam_10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_kill_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kill_remove.setObjectName("pushButton_kill_remove")
        self.verticalLayout.addWidget(self.pushButton_kill_remove)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_cross = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cross.sizePolicy().hasHeightForWidth())
        self.pushButton_cross.setSizePolicy(sizePolicy)
        self.pushButton_cross.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_cross.setObjectName("pushButton_cross")
        self.horizontalLayout_6.addWidget(self.pushButton_cross)
        self.pushButton_check = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_check.setObjectName("pushButton_check")
        self.horizontalLayout_6.addWidget(self.pushButton_check)
        self.pushButton_b_star = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_b_star.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_b_star.setObjectName("pushButton_b_star")
        self.horizontalLayout_6.addWidget(self.pushButton_b_star)
        self.pushButton_w_star = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_w_star.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_w_star.setObjectName("pushButton_w_star")
        self.horizontalLayout_6.addWidget(self.pushButton_w_star)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 175, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout_5.addWidget(self.pushButton_open)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adventure Wrench"))
        self.label_5.setText(_translate("MainWindow", "Current Encounter"))
        self.pushButton_Players.setText(_translate("MainWindow", "Edit Players"))
        self.pushButton_Encounter.setText(_translate("MainWindow", "DM Vault"))
        self.pushButton_toggle_expand.setText(_translate("MainWindow", "Expand/Collapse"))
        self.pushButton_Inititave.setText(_translate("MainWindow", "Advance Inititave"))
        self.label_2.setText(_translate("MainWindow", "Quick Change"))
        self.label_3.setText(_translate("MainWindow", "Initiative"))
        self.label_4.setText(_translate("MainWindow", "HP"))
        self.label.setText(_translate("MainWindow", "Damage"))
        self.pushButton_dam_1.setText(_translate("MainWindow", "-1"))
        self.pushButton_dam_3.setText(_translate("MainWindow", "-3"))
        self.pushButton_dam_5.setText(_translate("MainWindow", "-5"))
        self.pushButton_dam_10.setText(_translate("MainWindow", "-10"))
        self.pushButton_kill_remove.setText(_translate("MainWindow", "Kill/Remove"))
        self.pushButton_cross.setText(_translate("MainWindow", "✖"))
        self.pushButton_check.setText(_translate("MainWindow", "✔"))
        self.pushButton_b_star.setText(_translate("MainWindow", "★"))
        self.pushButton_w_star.setText(_translate("MainWindow", "☆"))
        self.pushButton_open.setText(_translate("MainWindow", "Open"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
