pyside6-uic Configurator.ui -o ../src/ui/Configurator.py
pyside6-uic Main_Window.ui -o ../src/ui/Main_Window.py
pyside6-uic Player_Dialog.ui -o ../src/ui/Player_Dialog.py
pyside6-uic template_actions.ui -o ../src/ui/template_actions.py
pyside6-uic template_attributes.ui -o ../src/ui/template_attributes.py
pyside6-uic template_descriptions.ui -o ../src/ui/template_descriptions.py
pyside6-uic Template_Dialog.ui -o ../src/ui/Template_Dialog.py
pyside6-uic Template_finder.ui -o ../src/ui/Template_finder.py
pyside6-uic template_items.ui -o ../src/ui/template_items.py
pyside6-uic template_roll_table.ui -o ../src/ui/template_roll_table.py
pyside6-uic template_stats.ui -o ../src/ui/template_stats.py
pyside6-uic Vault_Dialog.ui -o ../src/ui/Vault_Dialog.py
